version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway

  web:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chess_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  frontend:
    image: node:14
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"

volumes:
  db-data: {}
